### ISSUE TITLE
Support parallel processing for Model 4

### ISSUE THREAD

**Issue by JoelLinn** [matiasdelellis/facerecognition-external-model#5]
Model 4 should be easy to run on two cores, even with practically non-existent python parallelism.

**Comment by 36grad** [comment]
I have created a pull request that enables the facerecognition app to use multiple external model instances. So, while each external model will still be running on only one core, you can benefit from all cores you have.

See: https://github.com/matiasdelellis/facerecognition/pull/743

**Comment by doppelgrau** [comment]
Had made a "competing" one here in PR #20 where the container itself allows multiple connections.

**Comment by matiasdelellis** [comment]
Great. Thanks!.
Model 4 is not parallel, but since you can run multiple queries in parallel, I think the result is even better.
